# Generated by Django 3.2.5 on 2021-08-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210825_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='datetime_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
