# Generated by Django 3.2.5 on 2021-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_album_datetime_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Hold Shift Key to Select Multiple Genres', related_name='genre_albums', to='auctions.Genre'),
        ),
    ]
