# Generated by Django 3.2.5 on 2021-09-03 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210901_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
