# Generated by Django 3.2.5 on 2021-09-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment_datetime_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Hold Command/Control Key to Select Multiple Genres', related_name='albums', to='auctions.Genre'),
        ),
    ]
